# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: wasm-bindgen-action
      uses: jetli/wasm-bindgen-action@v0.2.0            
    - name: Build Cargo
      run: cargo build
      working-directory: decryption-mlm-wasm
    - name: Build WASM
      run: wasm-pack build --target web
      working-directory: decryption-mlm-wasm

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install
      run: npm install
      working-directory: decryption-mlm-vue3
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "decryption-mlm-wasm/pkg/"
        target: "decryption-mlm-vue3"
        flags: "-r"
    - run: npm run build
      working-directory: decryption-mlm-vue3
    - uses: actions/checkout@v3
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        folder: dist
        working-directory: ./decryption-mlm-vue3
            
