# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: cd wasm folder
      run: cd ./decryption-mlm-wasm
    - name: wasm-bindgen-action
      uses: jetli/wasm-bindgen-action@v0.2.0            
    - uses: actions/checkout@v3
    - name: Build Cargo
      run: cargo build
    - uses: actions/checkout@v3
    - name: Build WASM
      run: wasm-pack build --target web

    - name: cd vue folder
      run: cd ../decryption-mlm-vue
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install
      run: npm install
    - name: copy pkg folder
      run: cp ../decryption-mlm-wasm/pkg ./
    - run: npm run build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.4.3
      with:
        folder: dist
            
